### ISSUE TITLE
Unbound variable while executing the install script

### ISSUE THREAD

**Issue by SailReal** [nfirvine/osx-lock-on-remove-usb#1]
Tried to run the script in the console on os sierra and got the following error message: 
sudo ./install.sh 
./install.sh: line 2: $1: unbound variable

Do you have any idea whats going wrong?

**Comment by nfirvine** [comment]
Yep, I failed at Markdown. usage is `install.sh <vendor_id> <product_id>`. You can find those values in System Report.
